### ISSUE TITLE
front-end test integration with travis

### ISSUE THREAD

**Issue by micgro42** [dokufreaks/dokuwiki-plugin-wizard#3]
Hi,

I've written some front-end tests with qunit for the edittable plugin cosmocode/edittable#80 and managed to integrate it into Travis. The details are on the wikipage:  https://www.dokuwiki.org/devel%3Aunittesting#javascript_frontend-tests These tests require `npm` and `grunt`.

Can we / should we integrate this functionality into the plugin-wizard?

**Comment by Klap-in** [comment]
It will add some additional clutter for plugin authors. Therefore imho it makes sense to let it be optional. For unittest the pluginwizard has already a checkbox, what about adding another checkbox for adding frontendtests?

**Comment by splitbrain** [comment]
This repository is now obsolete (the wizard functionality has been merged with the dev plugin). For this reason I'm closing this issue. Feel free to reopen it (or send a PR) at https://github.com/dokuwiki/dokuwiki-plugin-dev
